# prometheus.yml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_app'
    static_configs:
      - targets: ['host.docker.internal:9464']  # for Mac/Windows
        # If you're on Linux, use: ['host.docker.internal:9464'] or 'host.docker.internal' may not resolve.
